// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cbejpntafxbtsvdsjgwk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNiZWpwbnRhZnhidHN2ZHNqZ3drIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzQ2NzM1MjgsImV4cCI6MjA5MDI0OTUyOH0.N1ReHdrohlUpde4Q82SrQsbVwiVfrt82-vI7ea2lvDk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});